services:
  app:
    container_name: climbing-live-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
      - app_var:/app/var
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "postgresql://climbing:climbing_secure_pwd@db:5432/climbing_live"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: climbing-live-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: climbing_live
      POSTGRES_USER: climbing
      POSTGRES_PASSWORD: climbing_secure_pwd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U climbing -d climbing_live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  app_var: