<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520122446 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mediamtx_api_url VARCHAR(255) NOT NULL, hls_base_url VARCHAR(255) NOT NULL, require_device_auth BOOLEAN NOT NULL, allow_unknown_devices BOOLEAN NOT NULL, auto_register_unknown_devices BOOLEAN NOT NULL, auto_authorize_new_devices BOOLEAN NOT NULL, expose_only_authorized_paths BOOLEAN NOT NULL, max_devices INT NOT NULL, max_connected_devices INT NOT NULL, device_offline_after_ms INT NOT NULL, poll_interval_ms INT NOT NULL, enable_publish BOOLEAN NOT NULL, enable_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE settings');
    }
}
